  services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      # Passe variáveis de build aqui se necessário:
      # args:
      #   NEXT_PUBLIC_API_URL: https://api.exemplo.com
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
